<?php

namespace covoiturage\userBundle\Repository;

/**
 * notificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notificationsRepository extends \Doctrine\ORM\EntityRepository
{
}
