<?php

namespace covoiturage\userBundle\Repository;

/**
 * reservationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reservationsRepository extends \Doctrine\ORM\EntityRepository
{
}
