covoituragemembre:
    resource: "@covoituragemembreBundle/Resources/config/routing.yml"
    prefix:   /

covoiturageadmin:
    resource: "@covoiturageadminBundle/Resources/config/routing.yml"
    prefix:   /

covoiturageuser:
    resource: "@covoiturageuserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

EndroidOpenWeatherMapBundle:
    resource:   "@EndroidOpenWeatherMapBundle/Controller/"
    type:       annotation
    prefix:     /openweathermap/api

captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"
